(library
 (name lambda_lib)
 (modules event lambda_handler runtime)
 (libraries apicommand catalog_lib cohttp-lwt-unix uri yojson base64)
 (preprocess (pps ppx_deriving_yojson lwt_ppx)))

(executable
 (name main)
 (public_name bootstrap)
 (modules main)
 (libraries lambda_lib apicommand catalog_lib lwt))