(test
 (name product_test)
 (libraries apicommand alcotest)
 (package api-command))

(test
 (name constant_time_test)
 (libraries apicommand alcotest)
 (package api-command))

(test
 (name log_test)
 (libraries apicommand alcotest)
 (package api-command))

(test
 (name ssrf_test)
 (libraries apicommand alcotest)
 (package api-command))

(test
 (name orders_manager_test)
 (libraries apicommand alcotest lwt lwt.unix)
 (package api-command))